//! Build script: embed the built-in emote name list into the WASM frontend.
//!
//! The emote GIFs live in `../assets/emotes/` (shared with the native crate,
//! which embeds them via `rust-embed`). We emit a sorted `&[&str]` of the file
//! stems so the frontend has the whitelist synchronously at startup — no
//! runtime manifest fetch, so `:name:` rewriting works on the very first
//! (backlog) render with no race.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let aliases = Path::new(&manifest_dir)
        .join("..")
        .join("assets")
        .join("emotes")
        .join("aliases.tsv");
    println!("cargo:rerun-if-changed={}", aliases.display());

    let raw = std::fs::read_to_string(&aliases)
        .unwrap_or_else(|e| panic!("read {}: {e}", aliases.display()));

    // (polish_stem, english_alias) pairs.
    let mut pairs: Vec<(String, String)> = raw
        .lines()
        .filter_map(|l| l.split_once('\t'))
        .map(|(pl, en)| (pl.trim().to_owned(), en.trim().to_owned()))
        .collect();
    pairs.sort();
    assert!(!pairs.is_empty(), "no rows in {}", aliases.display());

    // Union of both names (whitelist), sorted + deduped.
    let mut names: Vec<String> = pairs.iter().flat_map(|(p, e)| [p.clone(), e.clone()]).collect();
    names.sort();
    names.dedup();

    let mut out = String::from("// @generated by build.rs — do not edit.\n");
    out.push_str("pub static EMOTE_NAMES: &[&str] = &[\n");
    for name in &names {
        writeln!(out, "    {name:?},").expect("write");
    }
    out.push_str("];\n\n");

    // Any tag name (stem or English alias) -> Polish stem (= GIF file name).
    let mut stem_rows: Vec<(String, String)> = Vec::new();
    for (pl, en) in &pairs {
        stem_rows.push((pl.clone(), pl.clone()));
        if en != pl {
            stem_rows.push((en.clone(), pl.clone()));
        }
    }
    stem_rows.sort();
    out.push_str("pub static EMOTE_STEM: &[(&str, &str)] = &[\n");
    for (name, stem) in &stem_rows {
        writeln!(out, "    ({name:?}, {stem:?}),").expect("write");
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("emote_names.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
