//! Build script: embed the built-in emote name list into the WASM frontend.
//!
//! The emote GIFs live in `../assets/emotes/` (shared with the native crate,
//! which embeds them via `rust-embed`). We emit a sorted `&[&str]` of the file
//! stems so the frontend has the whitelist synchronously at startup — no
//! runtime manifest fetch, so `:name:` rewriting works on the very first
//! (backlog) render with no race.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let emotes_dir = Path::new(&manifest_dir)
        .join("..")
        .join("assets")
        .join("emotes");
    println!("cargo:rerun-if-changed={}", emotes_dir.display());

    let mut names: Vec<String> = std::fs::read_dir(&emotes_dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", emotes_dir.display()))
        .filter_map(Result::ok)
        .filter_map(|entry| entry.file_name().into_string().ok())
        .filter_map(|name| name.strip_suffix(".gif").map(ToOwned::to_owned))
        .collect();
    names.sort();
    assert!(
        !names.is_empty(),
        "no .gif emotes found in {}",
        emotes_dir.display()
    );

    let mut out = String::from("// @generated by build.rs — do not edit.\n");
    out.push_str("pub static EMOTE_NAMES: &[&str] = &[\n");
    for name in &names {
        writeln!(out, "    {name:?},").expect("write to String");
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("emote_names.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
