//! `E2eManager` — the single entry point the rest of the app uses to
//! drive the RPE2E protocol.
//!
//! Responsibilities:
//!
//! - own the long-term `Identity` and a handle to the `Keyring`
//! - encrypt outgoing plaintext into one or more wire-format lines
//! - decrypt an incoming wire-format line under the strict handle check
//! - build and dispatch KEYREQ (initiator side)
//! - answer KEYREQ with KEYRSP when policy allows (responder side)
//! - consume KEYRSP to install a trusted incoming session (initiator side)
//! - enforce per-peer rate limiting on outgoing KEYREQ
//!
//! The handshake key-agreement is X25519 over *ephemeral* keys carried in
//! both KEYREQ (`eph_x25519`) and KEYRSP (`ephemeral_pub`). The Ed25519
//! long-term identity is used only to sign/verify each handshake message;
//! it is never directly fed into ECDH (which would conflate two curves).
//! See `docs/plans/2026-04-11-rpee2e-implementation.md` §12b for the
//! rationale.

use std::collections::HashMap;
use std::sync::Mutex;
use std::time::{SystemTime, UNIX_EPOCH};

use hkdf::Hkdf;
use sha2::Sha256;
use x25519_dalek::{PublicKey as XPub, StaticSecret};

use crate::e2e::chunker::split_plaintext;
use crate::e2e::crypto::{
    aead::{self, SessionKey},
    ecdh,
    fingerprint::{fingerprint, Fingerprint},
    identity::Identity,
    sig,
};
use crate::e2e::error::{E2eError, Result};
use crate::e2e::handshake::{
    encode_keyreq, encode_keyrekey, encode_keyrsp, signed_keyreq_payload,
    signed_keyrekey_payload, signed_keyrsp_payload, KeyRekey, KeyReq, KeyRsp, RateLimiter,
};
use crate::e2e::keyring::{
    ChannelMode, IncomingSession, Keyring, PeerRecord, TrustStatus,
};
use crate::e2e::wire::{build_aad, fresh_msgid, WireChunk};
use crate::e2e::TS_TOLERANCE_SECS;

/// In-flight handshake state — the initiator's ephemeral X25519 secret,
/// held until the matching KEYRSP arrives. Stored as raw bytes because
/// `x25519_dalek::StaticSecret` is not `Clone` and we want a boring
/// `HashMap` value.
///
/// Do **not** derive `Debug` on types that hold the raw secret.
struct PendingHandshake {
    #[allow(dead_code, reason = "future diagnostics: pending channel listing")]
    channel: String,
    eph_x25519_secret: [u8; 32],
}

/// Inbound KEYREQ cached in Normal mode for a yet-unknown peer, so that a
/// subsequent `/e2e accept <nick>` can complete the handshake by producing
/// the KEYRSP that would have been sent immediately under `AutoAccept`.
///
/// Keyed by `(sender_handle, channel)` in `pending_inbound`.
#[derive(Debug, Clone)]
struct PendingInboundKeyReq {
    req: KeyReq,
}

/// An outbound REKEY CTCP ready to ship, paired with the target IRC handle
/// it must go to. Drained by `take_pending_rekey_sends` right after
/// `encrypt_outgoing` triggers a lazy rotation, so the caller can enqueue
/// the per-peer NOTICEs on the same tick.
#[derive(Debug, Clone)]
pub struct PendingRekeySend {
    pub target_handle: String,
    pub notice_text: String,
}

/// Info surfaced when a Normal-mode KEYREQ arrives from an as-yet-untrusted
/// peer. Drained by `take_pending_accept_requests` and rendered as a themed
/// prompt instructing the user to run `/e2e accept` or `/e2e decline`.
#[derive(Debug, Clone)]
pub struct PendingAcceptRequest {
    pub handle: String,
    pub channel: String,
}

/// Top-level E2E controller. One instance lives in `AppState` for the
/// lifetime of the process.
pub struct E2eManager {
    identity: Identity,
    keyring: Keyring,
    rate_limiter: Mutex<RateLimiter>,
    /// In-flight handshakes keyed by `(channel, keyreq_nonce)`. The
    /// responder doesn't echo the KEYREQ nonce in KEYRSP, so lookup in
    /// `handle_keyrsp` scans entries by channel.
    pending: Mutex<HashMap<(String, [u8; 16]), PendingHandshake>>,
    /// TOFU warnings generated by the handshake path (handle changed,
    /// fingerprint changed, or peer revoked). Drained by the IRC event
    /// dispatcher via `take_pending_trust_changes` and surfaced to the
    /// user as themed event messages.
    pending_trust_change: Mutex<Vec<PendingTrustNotice>>,
    /// Outbound REKEY CTCPs produced by a lazy rotation inside
    /// `encrypt_outgoing`. The input layer drains these right after each
    /// encrypt call and appends them to `AppState::pending_e2e_sends`,
    /// matching the KEYRSP dispatch pattern.
    pending_rekey_sends: Mutex<Vec<PendingRekeySend>>,
    /// Inbound KEYREQs cached in Normal mode when the peer is not yet
    /// trusted. Keyed by `(sender_handle, channel)`. Consumed by
    /// `accept_pending_inbound` when the user runs `/e2e accept`.
    pending_inbound: Mutex<HashMap<(String, String), PendingInboundKeyReq>>,
    /// Per-peer prompts surfaced when a Normal-mode KEYREQ is cached for
    /// later acceptance. Drained by `take_pending_accept_requests`.
    pending_accept_requests: Mutex<Vec<PendingAcceptRequest>>,
}

/// The outcome of evaluating a freshly-arrived peer identity against the
/// local keyring. Consumers use this to decide whether to accept the key,
/// show a warning, or hard-reject.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TrustChange {
    /// Never seen this peer before — safe to TOFU.
    New,
    /// Exact same (fingerprint, handle) as before — continue trusting.
    Known,
    /// Same fingerprint, but the peer's handle has changed since last time.
    /// UI should emit `[E2E] notice: known key <fp> appeared under new handle`.
    /// Until `/e2e reverify` the session must NOT be auto-installed.
    HandleChanged {
        old_handle: String,
        new_handle: String,
        fingerprint: Fingerprint,
    },
    /// Same handle, but a DIFFERENT fingerprint is being offered. This is
    /// the SSH-style warning case — the sharpest possible alarm. Block and
    /// wait for `/e2e reverify`.
    FingerprintChanged {
        handle: String,
        old_fp: Fingerprint,
        new_fp: Fingerprint,
    },
    /// Previously revoked — do not re-trust on a new KEYREQ/KEYRSP. Only
    /// `/e2e unrevoke` can restore.
    Revoked {
        handle: String,
        fingerprint: Fingerprint,
    },
}

/// A TOFU warning ready to be surfaced to the user. `channel` identifies
/// the buffer the warning belongs in (always the handshake channel, i.e.
/// the value from the KEYREQ/KEYRSP payload — never the IRC target, which
/// is our own nick for CTCP NOTICEs).
#[derive(Debug, Clone)]
pub struct PendingTrustNotice {
    pub handle: String,
    pub channel: String,
    pub change: TrustChange,
}

/// Outcome of attempting to decrypt an incoming wire-format line.
#[derive(Debug, Clone)]
pub enum DecryptOutcome {
    /// One plaintext fragment (single chunk). Callers concatenate across
    /// chunks at the UI layer; the protocol is stateless per chunk.
    Plaintext(String),
    /// The chunk is well-formed but we don't have a session key for this
    /// sender on this channel yet. Callers should consider sending a
    /// `KEYREQ` (subject to rate limiting).
    MissingKey { handle: String, channel: String },
    /// Security-level rejection: handle mismatch, replay window violation,
    /// AEAD failure, peer not trusted, etc. Callers should surface this as
    /// an e2e warning rather than as a normal message.
    Rejected(String),
}

impl E2eManager {
    /// Load the identity row from the keyring, or generate and persist a
    /// fresh one if none exists.
    pub fn load_or_init(keyring: Keyring) -> Result<Self> {
        let identity = if let Some((_pk, sk, _fp, _ts)) = keyring.load_identity()? {
            Identity::from_secret_bytes(&sk)
        } else {
            let id = Identity::generate()?;
            let pk = id.public_bytes();
            let sk = id.secret_bytes();
            let fp = fingerprint(&pk);
            let now = now_unix();
            keyring.save_identity(&pk, &sk, &fp, now)?;
            id
        };
        Ok(Self {
            identity,
            keyring,
            rate_limiter: Mutex::new(RateLimiter::new()),
            pending: Mutex::new(HashMap::new()),
            pending_trust_change: Mutex::new(Vec::new()),
            pending_rekey_sends: Mutex::new(Vec::new()),
            pending_inbound: Mutex::new(HashMap::new()),
            pending_accept_requests: Mutex::new(Vec::new()),
        })
    }

    /// Classify an incoming `(fingerprint, handle)` against the keyring.
    /// Read-only; never mutates. The ordering matters:
    ///
    /// 1. Look up by fingerprint. If present and revoked → `Revoked`.
    /// 2. Same fingerprint with a different `last_handle` → `HandleChanged`.
    /// 3. Same fingerprint and same handle → `Known`.
    /// 4. Fingerprint unknown, but the handle maps to a different
    ///    fingerprint in `e2e_peers` → `FingerprintChanged`.
    /// 5. Otherwise → `New` (safe to TOFU-pin).
    fn classify_peer_change(
        &self,
        new_fp: &Fingerprint,
        new_handle: &str,
    ) -> Result<TrustChange> {
        if let Some(existing) = self.keyring.get_peer_by_fingerprint(new_fp)? {
            if existing.global_status == TrustStatus::Revoked {
                return Ok(TrustChange::Revoked {
                    handle: new_handle.to_string(),
                    fingerprint: *new_fp,
                });
            }
            if existing.last_handle.as_deref() != Some(new_handle) {
                return Ok(TrustChange::HandleChanged {
                    old_handle: existing.last_handle.unwrap_or_default(),
                    new_handle: new_handle.to_string(),
                    fingerprint: *new_fp,
                });
            }
            return Ok(TrustChange::Known);
        }
        // Unknown fingerprint — check if the handle was previously owned by
        // a different identity.
        if let Some(existing) = self.keyring.get_peer_by_handle(new_handle)? {
            return Ok(TrustChange::FingerprintChanged {
                handle: new_handle.to_string(),
                old_fp: existing.fingerprint,
                new_fp: *new_fp,
            });
        }
        Ok(TrustChange::New)
    }

    /// Push a TOFU warning for later surfacing by the IRC dispatcher.
    fn record_trust_change(&self, notice: PendingTrustNotice) {
        self.pending_trust_change
            .lock()
            .expect("e2e pending trust change mutex poisoned")
            .push(notice);
    }

    /// Drain and return all pending TOFU warnings. The IRC event dispatcher
    /// calls this after every `handle_keyreq` / `handle_keyrsp` to surface
    /// the warnings to the user as themed event messages.
    pub fn take_pending_trust_changes(&self) -> Vec<PendingTrustNotice> {
        let mut guard = self
            .pending_trust_change
            .lock()
            .expect("e2e pending trust change mutex poisoned");
        std::mem::take(&mut *guard)
    }

    #[must_use]
    pub fn fingerprint(&self) -> Fingerprint {
        fingerprint(&self.identity.public_bytes())
    }

    #[must_use]
    pub fn keyring(&self) -> &Keyring {
        &self.keyring
    }

    #[must_use]
    pub fn identity_pub(&self) -> [u8; 32] {
        self.identity.public_bytes()
    }

    // ---------- encrypt outgoing ----------

    /// Encrypt `plaintext` for `channel` and return one wire-format line per
    /// chunk. Callers send these verbatim via PRIVMSG. Honors lazy rotation:
    /// if the outgoing session is flagged `pending_rotation`, a fresh key is
    /// generated first.
    pub fn encrypt_outgoing(&self, channel: &str, plaintext: &str) -> Result<Vec<String>> {
        let sk = self.get_or_generate_outgoing_key(channel)?;
        let chunks = split_plaintext(plaintext)?;
        let total_usize = chunks.len();
        let total = u8::try_from(total_usize).map_err(|_| E2eError::ChunkLimit(u8::MAX))?;
        if total == 0 {
            // split_plaintext always returns at least one chunk, but keep a
            // defensive check — `build_aad` and wire format require part ≥ 1.
            return Err(E2eError::Wire("chunker produced zero chunks".into()));
        }
        let msgid = fresh_msgid();
        let ts = now_unix();
        let mut out = Vec::with_capacity(total_usize);
        for (idx, plain) in chunks.iter().enumerate() {
            // idx is in 0..total, so idx+1 fits in u8 because total ≤ u8::MAX.
            let part = u8::try_from(idx + 1)
                .map_err(|_| E2eError::ChunkLimit(u8::MAX))?;
            let aad = build_aad(channel, msgid, ts, part, total);
            let (nonce, ct) = aead::encrypt(&sk, &aad, plain)?;
            let wire = WireChunk {
                msgid,
                ts,
                part,
                total,
                nonce,
                ciphertext: ct,
            };
            out.push(wire.encode()?);
        }
        Ok(out)
    }

    /// Return our outgoing session key for `channel`, creating one on
    /// first use. If the current session is flagged `pending_rotation`
    /// (spec §5.3 — set by `/e2e revoke` or `/e2e rotate`) a fresh key
    /// is generated AND a `REKEY` CTCP is queued for every remaining
    /// trusted peer on the channel. The queue is drained by the caller
    /// via `take_pending_rekey_sends`.
    fn get_or_generate_outgoing_key(&self, channel: &str) -> Result<SessionKey> {
        if let Some(sess) = self.keyring.get_outgoing_session(channel)?
            && !sess.pending_rotation
        {
            return Ok(sess.sk);
        }
        // Either no session yet, or the current one is flagged
        // `pending_rotation` (lazy rotate). Remember whether we need to
        // distribute before INSERT OR REPLACE clears the flag.
        let had_pending_rotation = self
            .keyring
            .get_outgoing_session(channel)?
            .is_some_and(|s| s.pending_rotation);
        let fresh = aead::generate_session_key()?;
        self.keyring
            .set_outgoing_session(channel, &fresh, now_unix())?;

        if had_pending_rotation {
            // Distribute the fresh key to every remaining recipient of
            // our outgoing key on this channel. The recipients table is
            // populated on each KEYRSP we serve and pruned on /e2e
            // revoke, so the list here is exactly the remaining peers
            // that need the new key (spec §5.3).
            let recipients = self.keyring.list_outgoing_recipients(channel)?;
            if !recipients.is_empty() {
                let mut queue = self
                    .pending_rekey_sends
                    .lock()
                    .expect("e2e pending rekey mutex poisoned");
                for (handle, fp) in recipients {
                    // Look up the peer row by fingerprint so we sign
                    // against the stored long-term Ed25519 pubkey.
                    let Some(peer) = self.keyring.get_peer_by_fingerprint(&fp)? else {
                        tracing::warn!(
                            "rekey: no peer row for fp={} (handle={}); skipping",
                            hex::encode(fp),
                            handle,
                        );
                        continue;
                    };
                    match self.build_rekey_for_peer(channel, &peer, &fresh) {
                        Ok(rk) => {
                            let body = format!("\x01{}\x01", encode_keyrekey(&rk));
                            queue.push(PendingRekeySend {
                                target_handle: handle,
                                notice_text: body,
                            });
                        }
                        Err(e) => {
                            tracing::warn!(
                                "rekey: build_rekey_for_peer failed for {handle}: {e}"
                            );
                        }
                    }
                }
            }
        }

        Ok(fresh)
    }

    /// Produce a `KeyRekey` CTCP delivering `new_sk` for `channel` to the
    /// given peer. A fresh X25519 ephemeral is generated; the peer's
    /// Ed25519 identity is converted to its Montgomery counterpart via
    /// the RFC 7748 birational map so the ECDH target is a stable key.
    fn build_rekey_for_peer(
        &self,
        channel: &str,
        peer: &PeerRecord,
        new_sk: &SessionKey,
    ) -> Result<KeyRekey> {
        // Fresh ephemeral X25519 from us (initiator of the distribution).
        let mut eph_sk_bytes = [0u8; 32];
        rand::fill(&mut eph_sk_bytes);
        let eph_sk = StaticSecret::from(eph_sk_bytes);
        let eph_pub = XPub::from(&eph_sk).to_bytes();

        // Derive the peer's X25519 public from their Ed25519 identity.
        let peer_x25519_pub = ecdh::ed25519_pub_to_x25519(&peer.pubkey)?;
        let shared = eph_sk.diffie_hellman(&XPub::from(peer_x25519_pub));

        // HKDF → 32-byte wrap key (same labels as the handshake path so
        // libsodium-based peers can reuse their existing wrap helpers,
        // with the `REKEY` info string acting as the domain separator).
        let info = rekey_info(channel);
        let hk = Hkdf::<Sha256>::new(Some(b"RPE2E01-WRAP"), shared.as_bytes());
        let mut wrap_key = [0u8; 32];
        hk.expand(info.as_bytes(), &mut wrap_key)
            .expect("hkdf expand 32 bytes never fails");

        let (wrap_nonce, wrap_ct) = aead::encrypt(&wrap_key, info.as_bytes(), new_sk)?;

        let mut nonce = [0u8; 16];
        rand::fill(&mut nonce);
        let pubkey = self.identity.public_bytes();
        let sig_payload = signed_keyrekey_payload(
            channel,
            &pubkey,
            &eph_pub,
            &wrap_nonce,
            &wrap_ct,
            &nonce,
        );
        let sig_bytes = sig::sign(self.identity.signing_key(), &sig_payload);

        Ok(KeyRekey {
            channel: channel.to_string(),
            pubkey,
            eph_pub,
            wrap_nonce,
            wrap_ct,
            nonce,
            sig: sig_bytes,
        })
    }

    /// Drain the queue of REKEY CTCPs that accumulated during the most
    /// recent `encrypt_outgoing` rotation. The caller (`app::input`) drains
    /// right after encrypt and enqueues each entry into `pending_e2e_sends`.
    pub fn take_pending_rekey_sends(&self) -> Vec<PendingRekeySend> {
        let mut guard = self
            .pending_rekey_sends
            .lock()
            .expect("e2e pending rekey mutex poisoned");
        std::mem::take(&mut *guard)
    }

    /// Drain the queue of Normal-mode pending-accept prompts accumulated
    /// during `handle_keyreq` for surfacing to the user.
    pub fn take_pending_accept_requests(&self) -> Vec<PendingAcceptRequest> {
        let mut guard = self
            .pending_accept_requests
            .lock()
            .expect("e2e pending accept requests mutex poisoned");
        std::mem::take(&mut *guard)
    }

    /// Consume an unsolicited REKEY CTCP from `sender_handle`. Verifies
    /// signature, runs TOFU classification, unwraps the session key using
    /// our Ed25519-derived X25519 secret, and installs it as the new
    /// trusted incoming session for `(sender_handle, channel)`.
    pub fn handle_rekey(&self, sender_handle: &str, rekey: &KeyRekey) -> Result<()> {
        // Verify signature first — no state touched until we're sure the
        // message is authentic against the pubkey it carries.
        let sig_payload = signed_keyrekey_payload(
            &rekey.channel,
            &rekey.pubkey,
            &rekey.eph_pub,
            &rekey.wrap_nonce,
            &rekey.wrap_ct,
            &rekey.nonce,
        );
        sig::verify(&rekey.pubkey, &sig_payload, &rekey.sig)?;

        // TOFU classification. A REKEY from a peer we've never seen is
        // rejected outright: legitimate lazy-rotate distribution always
        // happens to peers with whom we've already exchanged a handshake,
        // so an "unsolicited" REKEY from an unknown peer is either a
        // replay or an attacker.
        let new_fp = fingerprint(&rekey.pubkey);
        let change = self.classify_peer_change(&new_fp, sender_handle)?;
        match &change {
            TrustChange::New => {
                return Err(E2eError::Handshake(
                    "REKEY from unknown peer; ignoring".into(),
                ));
            }
            TrustChange::Known => {}
            TrustChange::HandleChanged { .. }
            | TrustChange::FingerprintChanged { .. }
            | TrustChange::Revoked { .. } => {
                let err = handle_mismatch_for(&change, sender_handle);
                self.record_trust_change(PendingTrustNotice {
                    handle: sender_handle.to_string(),
                    channel: rekey.channel.clone(),
                    change,
                });
                return Err(err);
            }
        }

        // Derive our X25519 secret from our Ed25519 seed and complete ECDH.
        let my_seed = self.identity.secret_bytes();
        let my_x25519_scalar = ecdh::ed25519_seed_to_x25519(&my_seed);
        let my_sk = StaticSecret::from(my_x25519_scalar);
        let shared = my_sk.diffie_hellman(&XPub::from(rekey.eph_pub));
        let info = rekey_info(&rekey.channel);
        let hk = Hkdf::<Sha256>::new(Some(b"RPE2E01-WRAP"), shared.as_bytes());
        let mut wrap_key = [0u8; 32];
        hk.expand(info.as_bytes(), &mut wrap_key)
            .expect("hkdf expand 32 bytes never fails");

        let new_sk_bytes = aead::decrypt(
            &wrap_key,
            &rekey.wrap_nonce,
            info.as_bytes(),
            &rekey.wrap_ct,
        )?;
        if new_sk_bytes.len() != 32 {
            return Err(E2eError::Crypto(format!(
                "rekey sk has unexpected length {}",
                new_sk_bytes.len()
            )));
        }
        let mut new_sk = [0u8; 32];
        new_sk.copy_from_slice(&new_sk_bytes);

        let sess = IncomingSession {
            handle: sender_handle.to_string(),
            channel: rekey.channel.clone(),
            fingerprint: new_fp,
            sk: new_sk,
            status: TrustStatus::Trusted,
            created_at: now_unix(),
        };
        self.keyring.install_incoming_session_strict(&sess)?;
        Ok(())
    }

    // ---------- decrypt incoming ----------

    /// Decrypt an incoming wire-format line. `sender_handle` **must** come
    /// from the raw IRC `user@host` prefix captured by the IRC parser —
    /// never from a field inside the encrypted payload. Strict handle check
    /// is what binds a session key to an on-wire identity.
    pub fn decrypt_incoming(
        &self,
        sender_handle: &str,
        channel: &str,
        wire_line: &str,
    ) -> Result<DecryptOutcome> {
        let Some(wire) = WireChunk::parse(wire_line)? else {
            // Not an RPE2E01 line at all — caller should render it as the
            // plain IRC text.
            return Ok(DecryptOutcome::Plaintext(wire_line.to_string()));
        };

        // Replay window check (application layer, on top of AEAD).
        let now = now_unix();
        let skew = (now - wire.ts).abs();
        if skew > TS_TOLERANCE_SECS {
            return Ok(DecryptOutcome::Rejected(format!(
                "ts outside tolerance window ({skew}s skew)"
            )));
        }

        let Some(sess) = self.keyring.get_incoming_session(sender_handle, channel)? else {
            return Ok(DecryptOutcome::MissingKey {
                handle: sender_handle.to_string(),
                channel: channel.to_string(),
            });
        };
        if sess.status != TrustStatus::Trusted {
            return Ok(DecryptOutcome::Rejected(format!(
                "peer not trusted (status={:?})",
                sess.status
            )));
        }

        let aad = build_aad(channel, wire.msgid, wire.ts, wire.part, wire.total);
        match aead::decrypt(&sess.sk, &wire.nonce, &aad, &wire.ciphertext) {
            Ok(pt) => match String::from_utf8(pt) {
                Ok(s) => Ok(DecryptOutcome::Plaintext(s)),
                Err(e) => Ok(DecryptOutcome::Rejected(format!("utf8: {e}"))),
            },
            Err(e) => Ok(DecryptOutcome::Rejected(format!("aead failed: {e}"))),
        }
    }

    // ---------- handshake initiator ----------

    /// Build a signed KEYREQ for `channel`, generating and stashing a fresh
    /// ephemeral X25519 secret. The secret is retrieved later in
    /// `handle_keyrsp` to derive the wrap key.
    pub fn build_keyreq(&self, channel: &str) -> Result<KeyReq> {
        let mut nonce = [0u8; 16];
        rand::fill(&mut nonce);

        let mut eph_secret = [0u8; 32];
        rand::fill(&mut eph_secret);
        let eph_pub = {
            let sec = StaticSecret::from(eph_secret);
            XPub::from(&sec).to_bytes()
        };

        let pubkey = self.identity.public_bytes();
        let sig_payload = signed_keyreq_payload(channel, &pubkey, &eph_pub, &nonce);
        let sig_bytes = sig::sign(self.identity.signing_key(), &sig_payload);

        self.pending
            .lock()
            .expect("e2e pending mutex poisoned")
            .insert(
                (channel.to_string(), nonce),
                PendingHandshake {
                    channel: channel.to_string(),
                    eph_x25519_secret: eph_secret,
                },
            );

        Ok(KeyReq {
            channel: channel.to_string(),
            pubkey,
            eph_x25519: eph_pub,
            nonce,
            sig: sig_bytes,
        })
    }

    /// Wrap a KEYREQ in CTCP framing ready for NOTICE dispatch.
    #[must_use]
    #[allow(
        clippy::unused_self,
        reason = "method form is kept for symmetry with the rest of the public API; \
                  future versions may bind per-instance state (e.g. NOTICE ID counters)"
    )]
    pub fn encode_keyreq_ctcp(&self, req: &KeyReq) -> String {
        format!("\x01{}\x01", encode_keyreq(req))
    }

    /// Rate-limit check for outgoing KEYREQ. Returns `true` if a request to
    /// `peer_handle` is allowed right now.
    pub fn allow_keyreq(&self, peer_handle: &str) -> bool {
        self.rate_limiter
            .lock()
            .expect("rate limiter mutex poisoned")
            .allow_outgoing(peer_handle)
    }

    // ---------- handshake responder ----------

    /// Handle an incoming KEYREQ. Returns `Some(KeyRsp)` ready to send back
    /// via NOTICE if policy allows, `None` if the request is silently
    /// ignored (channel disabled / quiet mode) or cached for `/e2e accept`
    /// (Normal mode). Returns `Err` only on protocol-level problems
    /// (bad signature, malformed field, TOFU failure).
    /// Return the effective mode for `channel` with autotrust applied, or
    /// `Ok(None)` if the channel is disabled. Keeps `handle_keyreq` compact.
    fn effective_channel_mode(
        &self,
        sender_handle: &str,
        channel: &str,
    ) -> Result<Option<ChannelMode>> {
        let Some(ch_cfg) = self.keyring.get_channel_config(channel)? else {
            return Ok(None);
        };
        if !ch_cfg.enabled {
            return Ok(None);
        }
        if self.keyring.autotrust_matches(sender_handle, channel)? {
            return Ok(Some(ChannelMode::AutoAccept));
        }
        Ok(Some(ch_cfg.mode))
    }

    /// Upsert the peer row on a New/Known KEYREQ, or record a trust-change
    /// notice + bail out on HandleChanged/FingerprintChanged/Revoked.
    fn tofu_upsert_on_keyreq(
        &self,
        sender_handle: &str,
        req: &KeyReq,
        fp: &Fingerprint,
    ) -> Result<()> {
        let now = now_unix();
        let change = self.classify_peer_change(fp, sender_handle)?;
        match change {
            TrustChange::New | TrustChange::Known => {
                let global_status = if matches!(change, TrustChange::Known) {
                    self.keyring
                        .get_peer_by_fingerprint(fp)?
                        .map_or(TrustStatus::Pending, |p| p.global_status)
                } else {
                    TrustStatus::Pending
                };
                let peer_rec = PeerRecord {
                    fingerprint: *fp,
                    pubkey: req.pubkey,
                    last_handle: Some(sender_handle.to_string()),
                    last_nick: None,
                    first_seen: now,
                    last_seen: now,
                    global_status,
                };
                self.keyring.upsert_peer(&peer_rec)?;
                Ok(())
            }
            TrustChange::HandleChanged { .. }
            | TrustChange::FingerprintChanged { .. }
            | TrustChange::Revoked { .. } => {
                let err_msg = handle_mismatch_for(&change, sender_handle);
                self.record_trust_change(PendingTrustNotice {
                    handle: sender_handle.to_string(),
                    channel: req.channel.clone(),
                    change,
                });
                Err(err_msg)
            }
        }
    }

    /// Cache an incoming Normal-mode KEYREQ and emit a pending-accept
    /// prompt. Installs a `Pending` incoming-session row so `/e2e list`
    /// surfaces the peer, stashes the full KEYREQ for later
    /// `accept_pending_inbound`, and queues a `PendingAcceptRequest`.
    fn cache_pending_inbound_normal_mode(
        &self,
        sender_handle: &str,
        req: &KeyReq,
        fp: &Fingerprint,
    ) {
        let pending_sess = IncomingSession {
            handle: sender_handle.to_string(),
            channel: req.channel.clone(),
            fingerprint: *fp,
            // Zero-filled placeholder. Row is `Pending`, so the decrypt
            // path rejects it before ever touching these bytes; it is
            // replaced on `/e2e accept` when the real KEYRSP session is
            // installed.
            sk: [0u8; 32],
            status: TrustStatus::Pending,
            created_at: now_unix(),
        };
        if let Err(e) = self.keyring.install_incoming_session_strict(&pending_sess) {
            tracing::warn!("normal-mode pending session install failed: {e}");
        }
        self.pending_inbound
            .lock()
            .expect("e2e pending inbound mutex poisoned")
            .insert(
                (sender_handle.to_string(), req.channel.clone()),
                PendingInboundKeyReq { req: req.clone() },
            );
        self.pending_accept_requests
            .lock()
            .expect("e2e pending accept mutex poisoned")
            .push(PendingAcceptRequest {
                handle: sender_handle.to_string(),
                channel: req.channel.clone(),
            });
    }

    pub fn handle_keyreq(&self, sender_handle: &str, req: &KeyReq) -> Result<Option<KeyRsp>> {
        // Verify signature over the full KEYREQ payload, binding `eph_x25519`.
        let sig_payload =
            signed_keyreq_payload(&req.channel, &req.pubkey, &req.eph_x25519, &req.nonce);
        sig::verify(&req.pubkey, &sig_payload, &req.sig)?;

        // Channel config + autotrust mode promotion.
        let Some(effective_mode) = self.effective_channel_mode(sender_handle, &req.channel)?
        else {
            return Ok(None);
        };

        // TOFU classification: only safe outcomes (New / Known) proceed to
        // the upsert; warning outcomes record a PendingTrustNotice and bail.
        let fp = fingerprint(&req.pubkey);
        self.tofu_upsert_on_keyreq(sender_handle, req, &fp)?;

        // Policy gate (spec §5.2). Normal-mode unknown peers are cached
        // for later `/e2e accept`; Quiet-mode unknown peers are dropped.
        let already_trusted = self
            .keyring
            .get_incoming_session(sender_handle, &req.channel)?
            .is_some_and(|s| s.status == TrustStatus::Trusted);
        let allow = match effective_mode {
            ChannelMode::AutoAccept => true,
            ChannelMode::Normal => {
                if already_trusted {
                    true
                } else {
                    self.cache_pending_inbound_normal_mode(sender_handle, req, &fp);
                    return Ok(None);
                }
            }
            ChannelMode::Quiet => already_trusted,
        };
        if !allow {
            return Ok(None);
        }

        // Our outgoing channel key is what we wrap and hand the peer so
        // they can decrypt our future messages.
        let our_sk = self.get_or_generate_outgoing_key(&req.channel)?;

        // Record the peer as a recipient of our outgoing key on this
        // channel so the lazy-rotate distribution loop knows to push a
        // fresh key to them on the next `/e2e revoke` rotation.
        self.keyring.record_outgoing_recipient(
            &req.channel,
            sender_handle,
            &fingerprint(&req.pubkey),
            now_unix(),
        )?;

        // Fresh ephemeral X25519 keypair for ECDH with the initiator's
        // ephemeral public.
        let mut our_eph_secret = [0u8; 32];
        rand::fill(&mut our_eph_secret);
        let our_eph_sec = StaticSecret::from(our_eph_secret);
        let our_eph_pub = XPub::from(&our_eph_sec).to_bytes();

        // `info` (and AEAD `aad`) must be computable identically by both
        // sides. We deliberately omit `sender_handle` here because the
        // initiator does not know its own server-assigned handle at the
        // point it calls `handle_keyrsp`. The ephemeral X25519 keypairs
        // themselves bind the exchange to a specific peer.
        let info = wrap_info(&req.channel);
        let wrap_key = derive_wrap_key(&our_eph_sec, &req.eph_x25519, info.as_bytes());
        let (wrap_nonce, wrap_ct) = aead::encrypt(&wrap_key, info.as_bytes(), &our_sk)?;

        // Sign response. `pubkey` is our long-term Ed25519 identity; it is
        // bound into the signature so the initiator can verify the KEYRSP
        // against the exact pubkey the responder claims and TOFU-pin that
        // pubkey in one atomic step.
        let our_pubkey = self.identity.public_bytes();
        let mut rsp_nonce = [0u8; 16];
        rand::fill(&mut rsp_nonce);
        let sig_payload = signed_keyrsp_payload(
            &req.channel,
            &our_pubkey,
            &our_eph_pub,
            &wrap_nonce,
            &wrap_ct,
            &rsp_nonce,
        );
        let sig_bytes = sig::sign(self.identity.signing_key(), &sig_payload);

        // We have also just shipped *our own* outgoing session to the peer.
        // Record an incoming-session row on our side pointing at the
        // initiator so that when they start sending encrypted PRIVMSGs we
        // can decrypt them — except we don't know *their* key yet because
        // in this model the two sides each use their own outgoing key. The
        // peer's future KEYREQ→KEYRSP (or the reciprocal of this one
        // initiated by us) installs the other direction.
        //
        // NOTE: this v1 model is "unidirectional per KEYREQ"; a fully
        // symmetric exchange requires either side to send its own KEYREQ.
        // The integration tests only drive one direction.

        Ok(Some(KeyRsp {
            channel: req.channel.clone(),
            pubkey: our_pubkey,
            ephemeral_pub: our_eph_pub,
            wrap_nonce,
            wrap_ct,
            nonce: rsp_nonce,
            sig: sig_bytes,
        }))
    }

    /// Complete a Normal-mode pending KEYREQ by running the full
    /// auto-accept branch against the cached request. Returns the
    /// generated `KeyRsp` so the caller can enqueue it for dispatch.
    ///
    /// Returns `Ok(None)` if no pending inbound KEYREQ exists for this
    /// `(handle, channel)` — the `/e2e accept` command uses that return
    /// shape to emit a "nothing to accept" error message.
    pub fn accept_pending_inbound(
        &self,
        sender_handle: &str,
        channel: &str,
    ) -> Result<Option<KeyRsp>> {
        let cached = {
            let mut guard = self
                .pending_inbound
                .lock()
                .expect("e2e pending inbound mutex poisoned");
            guard.remove(&(sender_handle.to_string(), channel.to_string()))
        };
        let Some(PendingInboundKeyReq { req }) = cached else {
            return Ok(None);
        };

        // Promote the stored row to trusted now so the subsequent
        // `handle_keyreq` re-entry sees `already_trusted = true` and
        // takes the AutoAccept path. The strict installer above already
        // seeded the row with the real fingerprint.
        self.keyring
            .update_incoming_status(sender_handle, channel, TrustStatus::Trusted)?;

        // Re-enter `handle_keyreq` under AutoAccept semantics. We cannot
        // just mark the channel config, so we temporarily cache the
        // channel's real config, force AutoAccept, run the branch, and
        // restore. Simpler: call a dedicated internal branch that is the
        // body of the AutoAccept arm, sharing the same crypto path.
        self.build_keyrsp_for_accepted_request(sender_handle, &req)
            .map(Some)
    }

    /// Build a KEYRSP for an already-vetted KEYREQ (TOFU classification
    /// done, channel enabled, caller has decided the peer is trusted).
    /// Shared between the `AutoAccept` branch of `handle_keyreq` and the
    /// `accept_pending_inbound` path.
    fn build_keyrsp_for_accepted_request(
        &self,
        sender_handle: &str,
        req: &KeyReq,
    ) -> Result<KeyRsp> {
        // Re-upsert the peer row with Trusted status (Normal-mode cache
        // wrote Pending, and we are now promoting).
        let fp = fingerprint(&req.pubkey);
        let now = now_unix();
        let existing_peer = self.keyring.get_peer_by_fingerprint(&fp)?;
        let peer_rec = PeerRecord {
            fingerprint: fp,
            pubkey: req.pubkey,
            last_handle: Some(sender_handle.to_string()),
            last_nick: existing_peer.as_ref().and_then(|p| p.last_nick.clone()),
            first_seen: existing_peer.as_ref().map_or(now, |p| p.first_seen),
            last_seen: now,
            global_status: TrustStatus::Trusted,
        };
        self.keyring.upsert_peer(&peer_rec)?;

        // Our outgoing channel key — possibly triggers lazy rotate.
        let our_sk = self.get_or_generate_outgoing_key(&req.channel)?;

        // Record the peer as a recipient of our outgoing key (accept path).
        self.keyring
            .record_outgoing_recipient(&req.channel, sender_handle, &fp, now_unix())?;

        // Fresh ephemeral X25519 keypair for ECDH.
        let mut our_eph_secret = [0u8; 32];
        rand::fill(&mut our_eph_secret);
        let our_eph_sec = StaticSecret::from(our_eph_secret);
        let our_eph_pub = XPub::from(&our_eph_sec).to_bytes();

        let info = wrap_info(&req.channel);
        let wrap_key = derive_wrap_key(&our_eph_sec, &req.eph_x25519, info.as_bytes());
        let (wrap_nonce, wrap_ct) = aead::encrypt(&wrap_key, info.as_bytes(), &our_sk)?;

        let our_pubkey = self.identity.public_bytes();
        let mut rsp_nonce = [0u8; 16];
        rand::fill(&mut rsp_nonce);
        let sig_payload = signed_keyrsp_payload(
            &req.channel,
            &our_pubkey,
            &our_eph_pub,
            &wrap_nonce,
            &wrap_ct,
            &rsp_nonce,
        );
        let sig_bytes = sig::sign(self.identity.signing_key(), &sig_payload);

        Ok(KeyRsp {
            channel: req.channel.clone(),
            pubkey: our_pubkey,
            ephemeral_pub: our_eph_pub,
            wrap_nonce,
            wrap_ct,
            nonce: rsp_nonce,
            sig: sig_bytes,
        })
    }

    /// Wrap a KEYRSP in CTCP framing ready for NOTICE dispatch.
    #[must_use]
    #[allow(
        clippy::unused_self,
        reason = "method form is kept for symmetry with the rest of the public API"
    )]
    pub fn encode_keyrsp_ctcp(&self, rsp: &KeyRsp) -> String {
        format!("\x01{}\x01", encode_keyrsp(rsp))
    }

    /// Wrap a REKEY in CTCP framing ready for NOTICE dispatch. Used by
    /// tests; the `encrypt_outgoing` lazy-rotate path queues pre-wrapped
    /// bodies directly into `pending_rekey_sends`.
    #[must_use]
    #[allow(
        clippy::unused_self,
        reason = "method form is kept for symmetry with the rest of the public API"
    )]
    pub fn encode_keyrekey_ctcp(&self, rk: &KeyRekey) -> String {
        format!("\x01{}\x01", encode_keyrekey(rk))
    }

    // ---------- handshake initiator (KEYRSP consumer) ----------

    /// Consume an incoming KEYRSP. The responder's long-term Ed25519 public
    /// key is carried on the wire inside `rsp.pubkey`; we verify the
    /// signature against it and simultaneously TOFU-pin that pubkey in the
    /// peer table. The initiator no longer needs to know the responder's
    /// pubkey out-of-band. We then look up our pending ephemeral secret,
    /// complete the ECDH, unwrap the session key, and install it as a
    /// *trusted* incoming session — the initiator already consented by
    /// having sent the KEYREQ in the first place.
    pub fn handle_keyrsp(&self, sender_handle: &str, rsp: &KeyRsp) -> Result<()> {
        // The pubkey the initiator will verify against is the one embedded
        // in the response. Signature binding on `rsp.pubkey` (see
        // `sig_payload_keyrsp`) means a MitM cannot swap it.
        let sender_pubkey = rsp.pubkey;

        // Verify signature first, before touching any state.
        let sig_payload = signed_keyrsp_payload(
            &rsp.channel,
            &sender_pubkey,
            &rsp.ephemeral_pub,
            &rsp.wrap_nonce,
            &rsp.wrap_ct,
            &rsp.nonce,
        );
        sig::verify(&sender_pubkey, &sig_payload, &rsp.sig)?;

        // Find matching pending handshake by channel. v1 allows at most one
        // in-flight handshake per channel at a time — this is fine in
        // practice given the 30-second per-peer rate limit.
        let mut pending = self.pending.lock().expect("e2e pending mutex poisoned");
        let key_to_remove = pending
            .iter()
            .find(|(k, _)| k.0 == rsp.channel)
            .map(|(k, _)| k.clone());
        let key = key_to_remove
            .ok_or_else(|| E2eError::Handshake("no pending handshake for channel".into()))?;
        let ph = pending
            .remove(&key)
            .expect("just found the key above, cannot be absent");
        drop(pending);

        // Derive wrap key from our stored ephemeral secret + peer's
        // ephemeral public. `info` must match exactly what the responder
        // used — see `handle_keyreq` for the rationale on handle omission.
        let info = wrap_info(&rsp.channel);
        let our_sec = StaticSecret::from(ph.eph_x25519_secret);
        let wrap_key = derive_wrap_key(&our_sec, &rsp.ephemeral_pub, info.as_bytes());

        // Unwrap the session key.
        let sk_bytes = aead::decrypt(&wrap_key, &rsp.wrap_nonce, info.as_bytes(), &rsp.wrap_ct)?;
        if sk_bytes.len() != 32 {
            return Err(E2eError::Crypto(format!(
                "unwrapped sk has unexpected length {}",
                sk_bytes.len()
            )));
        }
        let mut sk = [0u8; 32];
        sk.copy_from_slice(&sk_bytes);

        // TOFU classification on the responder's long-term pubkey. Only
        // New / Known outcomes auto-install a trusted session. Every other
        // outcome records a PendingTrustNotice and bails with
        // HandleMismatch so the caller surfaces a warning to the user.
        let fp = fingerprint(&sender_pubkey);
        let now = now_unix();
        let change = self.classify_peer_change(&fp, sender_handle)?;
        match change {
            TrustChange::New | TrustChange::Known => {
                self.keyring.upsert_peer(&PeerRecord {
                    fingerprint: fp,
                    pubkey: sender_pubkey,
                    last_handle: Some(sender_handle.to_string()),
                    last_nick: None,
                    first_seen: now,
                    last_seen: now,
                    // Sending our own KEYREQ is explicit consent — we
                    // always upgrade the peer to Trusted on a successful
                    // KEYRSP consumption. Known already-Trusted rows stay
                    // Trusted; brand-new peers become Trusted here.
                    global_status: TrustStatus::Trusted,
                })?;
            }
            TrustChange::HandleChanged { .. }
            | TrustChange::FingerprintChanged { .. }
            | TrustChange::Revoked { .. } => {
                let err = handle_mismatch_for(&change, sender_handle);
                self.record_trust_change(PendingTrustNotice {
                    handle: sender_handle.to_string(),
                    channel: rsp.channel.clone(),
                    change,
                });
                return Err(err);
            }
        }

        // Install the session under strict TOFU. A second KEYRSP for the
        // same (handle, channel) with a different fingerprint gets
        // rejected here as a second line of defense — the classifier above
        // already caught the common case via `e2e_peers` lookup, but
        // `install_incoming_session_strict` also blocks the edge case
        // where the peer row is fresh/inconsistent but the incoming
        // session row carries a different fingerprint.
        let sess = IncomingSession {
            handle: sender_handle.to_string(),
            channel: rsp.channel.clone(),
            fingerprint: fp,
            sk,
            status: TrustStatus::Trusted,
            created_at: now,
        };
        if let Err(e) = self.keyring.install_incoming_session_strict(&sess) {
            if matches!(e, E2eError::HandleMismatch { .. }) {
                // Surface as a FingerprintChanged notice.
                let existing_fp = self
                    .keyring
                    .get_incoming_session(sender_handle, &rsp.channel)?
                    .map(|s| s.fingerprint)
                    .unwrap_or_default();
                self.record_trust_change(PendingTrustNotice {
                    handle: sender_handle.to_string(),
                    channel: rsp.channel.clone(),
                    change: TrustChange::FingerprintChanged {
                        handle: sender_handle.to_string(),
                        old_fp: existing_fp,
                        new_fp: fp,
                    },
                });
            }
            return Err(e);
        }
        Ok(())
    }
}

/// Build the `E2eError::HandleMismatch` that corresponds to a rejected
/// `TrustChange`. The `expected`/`got` fields carry a human-readable
/// summary that the IRC dispatcher ignores — it prefers the richer
/// `PendingTrustNotice`. This error exists so that callers which aren't
/// the IRC dispatcher (tests, library consumers) still see a distinct
/// Err(...) return rather than a silent success.
fn handle_mismatch_for(change: &TrustChange, got_handle: &str) -> E2eError {
    let expected = match change {
        TrustChange::HandleChanged { old_handle, .. } => old_handle.clone(),
        TrustChange::FingerprintChanged { handle, old_fp, .. } => {
            format!("{handle} (fp={})", hex::encode(old_fp))
        }
        TrustChange::Revoked { handle, fingerprint } => {
            format!("{handle} (revoked, fp={})", hex::encode(fingerprint))
        }
        TrustChange::New | TrustChange::Known => String::new(),
    };
    E2eError::HandleMismatch {
        expected,
        got: got_handle.to_string(),
    }
}

/// Canonical HKDF `info` / AEAD `aad` for the handshake wrap step. Must be
/// computable identically by both initiator and responder from data they
/// already have. We bind only the channel; the ephemeral X25519 keypairs
/// already bind the exchange to a specific peer pair.
fn wrap_info(channel: &str) -> String {
    format!("RPE2E01-WRAP:{channel}")
}

/// Canonical HKDF `info` / AEAD `aad` for the REKEY distribution wrap.
/// The distinct `REKEY` prefix is a hard domain separator so a leaked
/// KEYRSP wrap cannot be replayed as a REKEY (and vice versa) even if an
/// attacker somehow produced the same ECDH shared.
fn rekey_info(channel: &str) -> String {
    format!("RPE2E01-REKEY:{channel}")
}

/// Derive a 32-byte wrap key from a pair of ephemeral X25519 keys. Matches
/// the same HKDF construction used by `crypto::ecdh::EphemeralKeypair`.
fn derive_wrap_key(secret: &StaticSecret, peer_pub_bytes: &[u8; 32], info: &[u8]) -> [u8; 32] {
    let peer_pub = XPub::from(*peer_pub_bytes);
    let shared = secret.diffie_hellman(&peer_pub);
    let hk = Hkdf::<Sha256>::new(Some(b"RPE2E01-WRAP"), shared.as_bytes());
    let mut okm = [0u8; 32];
    hk.expand(info, &mut okm)
        .expect("hkdf expand 32 bytes never fails for OKM ≤ 255 * HashLen");
    okm
}

fn now_unix() -> i64 {
    // SystemTime can technically be before UNIX_EPOCH on misconfigured
    // systems; in that case we fall back to 0. The replay-window check
    // works relatively, so a consistent-but-wrong clock still keeps both
    // sides in sync. AEAD is the real authenticity guarantee.
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |d| i64::try_from(d.as_secs()).unwrap_or(i64::MAX))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::e2e::keyring::Keyring;
    use rusqlite::Connection;
    use std::sync::{Arc, Mutex as StdMutex};

    const SCHEMA: &str = "
        CREATE TABLE e2e_identity (id INTEGER PRIMARY KEY CHECK (id = 1), pubkey BLOB NOT NULL, privkey BLOB NOT NULL, fingerprint BLOB NOT NULL, created_at INTEGER NOT NULL);
        CREATE TABLE e2e_peers (fingerprint BLOB PRIMARY KEY, pubkey BLOB NOT NULL, last_handle TEXT, last_nick TEXT, first_seen INTEGER NOT NULL, last_seen INTEGER NOT NULL, global_status TEXT NOT NULL DEFAULT 'pending');
        CREATE TABLE e2e_outgoing_sessions (channel TEXT PRIMARY KEY, sk BLOB NOT NULL, created_at INTEGER NOT NULL, pending_rotation INTEGER NOT NULL DEFAULT 0);
        CREATE TABLE e2e_incoming_sessions (handle TEXT NOT NULL, channel TEXT NOT NULL, fingerprint BLOB NOT NULL, sk BLOB NOT NULL, status TEXT NOT NULL DEFAULT 'pending', created_at INTEGER NOT NULL, PRIMARY KEY (handle, channel));
        CREATE TABLE e2e_channel_config (channel TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 0, mode TEXT NOT NULL DEFAULT 'normal');
        CREATE TABLE e2e_autotrust (id INTEGER PRIMARY KEY AUTOINCREMENT, scope TEXT NOT NULL, handle_pattern TEXT NOT NULL, created_at INTEGER NOT NULL, UNIQUE(scope, handle_pattern));
        CREATE TABLE e2e_outgoing_recipients (channel TEXT NOT NULL, handle TEXT NOT NULL, fingerprint BLOB NOT NULL, first_sent_at INTEGER NOT NULL, PRIMARY KEY (channel, handle));
    ";

    fn make_manager() -> E2eManager {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(SCHEMA).unwrap();
        let kr = Keyring::new(Arc::new(StdMutex::new(conn)));
        E2eManager::load_or_init(kr).unwrap()
    }

    #[test]
    fn load_or_init_persists_identity() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(SCHEMA).unwrap();
        let shared = Arc::new(StdMutex::new(conn));

        let kr1 = Keyring::new(shared.clone());
        let m1 = E2eManager::load_or_init(kr1).unwrap();
        let pk1 = m1.identity_pub();

        let kr2 = Keyring::new(shared);
        let m2 = E2eManager::load_or_init(kr2).unwrap();
        let pk2 = m2.identity_pub();

        assert_eq!(pk1, pk2, "identity must persist across loads");
    }

    #[test]
    fn build_keyreq_stores_pending_and_is_signed() {
        let mgr = make_manager();
        let req = mgr.build_keyreq("#x").unwrap();
        // Signature verifies with the same pubkey embedded in the KEYREQ.
        let payload = signed_keyreq_payload("#x", &req.pubkey, &req.eph_x25519, &req.nonce);
        sig::verify(&req.pubkey, &payload, &req.sig).unwrap();
        // Pending map has exactly one entry.
        assert_eq!(
            mgr.pending
                .lock()
                .expect("pending mutex poisoned in test")
                .len(),
            1
        );
    }

    #[test]
    fn encrypt_decrypt_requires_session() {
        let mgr = make_manager();
        // No incoming session installed → decrypt_incoming returns MissingKey.
        let wire = mgr
            .encrypt_outgoing("#x", "hi")
            .unwrap()
            .remove(0);
        let outcome = mgr.decrypt_incoming("~alice@host", "#x", &wire).unwrap();
        match outcome {
            DecryptOutcome::MissingKey { .. } => {}
            other => panic!("expected MissingKey, got {other:?}"),
        }
    }
}
